### ISSUE TITLE
Use jbcrypt

### ISSUE THREAD

**Issue by benmccann** [wsargent/play-shiro#8]
I usually hear that's it's most recommended to use bcrypt for password hashing.

E.g. here's [a post](http://security.stackexchange.com/questions/65238/password-storage-with-jasypt-strongpasswordencryptor-vs-pbkdf2) which recommends bcypt over jasypt

**Comment by wsargent** [comment]
Done.

**Comment by benmccann** [comment]
nice! thanks :-)
